### ISSUE TITLE
Navbar Links need to be refactored or titled diferently

### ISSUE THREAD

**Issue by ankitjavalkar** [FOSSEE/workshop_booking#91]
- ```Manage Workshops``` points to the homepage (post login) which essentially provides no information. Maybe this should point to the ```/my_workshops/``` page
- ```Workshop status``` should be reworded to ```Manage Workshops``` or only ```Workshops```
- ```Create Workshop``` should be renamed to ```Propose Workshop```

**Comment by CruiseDevice** [comment]
Fixed in #122
